core/urls.py
from django.urls import path, include
from core import views

app_name = "core"

urlpatterns = [
    # HomePage
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # Category
    path("category/", views.category_list_view, name="category-list"),
    path(
        "category/<cid>/",
        views.category_product_list_view,
        name="category-product-list",
    ),
    # vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail_view, name="vendor-detail"),
    # Tags
    path("products/tag/<slug:tag_slug>", views.tag_list, name="tags"),
    # Add Review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),
    # Search Functionality
    path("search/", views.search_view, name="search"),
    # for Filter
    path("filter-products/", views.filter_product, name="filter-product"),
    # Add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    # Cart page url
    path("cart/", views.cart_view, name="cart"),
    # Delete item from cart
    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),
    # Update cart
    path("update-cart/", views.update_cart, name="update-cart"),
    # checkout url
    path("checkout/", views.checkout_view, name="checkout"),
    # Paypal url
    path("paypal/", include("paypal.standard.ipn.urls")),
    # Payment success
    path("payment-completed/", views.payment_completed_view, name="payment-completed"),
    # Payment failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),
    # Customer dashboard
    path("dashboard/", views.customer_dashboard, name="dashboard"),
    # Order detail
    path("dashboard/order/<int:id>/", views.order_detail, name="order-detail"),
    # Address Defaul maker
    path(
        "make-default-address/", views.make_default_address, name="make-default-address"
    ),
    # Wishlist url
    path("wishlist/", views.wishlist_view, name="wishlist"),
    # Adding to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    # Deleting product from wihslist
    path("remove-from-wishlist/", views.remove_wishlist, name="remove-from-wishlist"),
    # contact-page
    path("contact/", views.contact, name="contact"),
    # contact-form ajax
    path("ajax-contact-form/", views.ajax_contact, name="ajax-contact-form"),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("profile/update/", views.profile_update, name="profile-update"),
]

core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Write a review..."})
    )

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.db.models import Count, Avg
from taggit.models import Tag
from core.models import (
    Product,
    Category,
    Vendor,
    CartOrder,
    CartOrderItems,
    ProductImages,
    ProductReview,
    Wishlist,
    Address,
)
from userauths.models import ContactUs, Profile
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages

import calendar
from django.db.models.functions import ExtractMonth
from django.core import serializers
from django.contrib.auth.decorators import login_required

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.


def index(request):
    products = Product.objects.filter(product_status="published", featured=True)

    context = {"products": products}

    return render(request, "core/index.html", context)


def product_list_view(request):
    products = Product.objects.filter(product_status="published")

    context = {"products": products}

    return render(request, "core/product-list.html", context)


def category_list_view(request):
    categories = Category.objects.all()

    context = {"categories": categories}

    return render(request, "core/category-list.html", context)


def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)

    context = {"category": category, "products": products}

    return render(request, "core/category-product-list.html", context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {"vendors": vendors}

    return render(request, "core/vendor-list.html", context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    context = {"vendor": vendor, "products": products}

    return render(request, "core/vendor-detail.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # Getting all Reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Getting average reviews
    average_rating = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    p_image = product.p_images.all()

    # Product Review form
    review_form = ProductReviewForm

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(
            user=request.user, product=product
        ).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "p": product,
        "products": products,
        "average_rating": average_rating,
        "make_review": make_review,
        "p_image": p_image,
        "review_form": review_form,
        "reviews": reviews,
    }

    return render(request, "core/product-detail.html", context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag,
    }

    return render(request, "core/tag.html", context)


def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"],
    )

    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    return JsonResponse(
        {"bool": True, "context": context, "average_reviews": average_reviews}
    )


def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(
        title__icontains=query, description__icontains=query
    ).order_by("-date")

    context = {"products": products, "query": query}

    return render(request, "core/search.html", context)


def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET["min_price"]
    max_price = request.GET["max_price"]

    products = (
        Product.objects.filter(product_status="published").order_by("-id").distinct()
    )

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/product-list.html", {"products": products})
    return JsonResponse({"data": data})


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET["id"])] = {
        "title": request.GET["title"],
        "qty": request.GET["qty"],
        "price": request.GET["price"],
        "image": request.GET["image"],
        "pid": request.GET["pid"],
        "price": request.GET["price"],
    }

    if "cart_data_obj" in request.session:
        if str(request.GET["id"]) in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            cart_data[str(request.GET["id"])]["qty"] = int(
                cart_product[str(request.GET["id"])]["qty"]
            )
            cart_data.update(cart_data)
            request.session["cart_data_obj"] = cart_data
        else:
            cart_data = request.session["cart_data_obj"]
            cart_data.update(cart_product)
            request.session["cart_data_obj"] = cart_data

    else:
        request.session["cart_data_obj"] = cart_product
    return JsonResponse(
        {
            "data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),
        }
    )


# def cart_view(request):
#     cart_total_amount = 0
#     if "cart_data_obj" in request.session:
#         for p_id, item in request.session["cart_data_obj"].items():
#             cart_total_amount += int(item["qty"]) * float(item["price"])
#         return render(
#             request,
#             "core/cart.html",
#             {
#                 "cart_data": request.session[
#                     "cart_data_obj"
#                 ],  # Corrected variable name
#                 "totalcartitems": len(request.session["cart_data_obj"]),
#                 "cart_total_amount": cart_total_amount,
#             },
#         )
#     else:
#         messages.warning(request, "Your cart is empty")
#         return redirect("core:index")


def cart_view(request):
    cart_total_amount = 0
    currency_symbol = "₹"  # Define the currency symbol used in your application
    if "cart_data_obj" in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            # Extract numeric part of the price string and remove currency symbol
            price = item["price"].replace(currency_symbol, "").strip()
            # Convert cleaned price string to float
            try:
                cart_total_amount += int(item["qty"]) * float(price)
            except ValueError:
                # Handle cases where the price string cannot be converted to float
                # You may want to log or handle this error appropriately
                pass
        return render(
            request,
            "core/cart.html",
            {
                "cart_data": request.session[
                    "cart_data_obj"
                ],  # Corrected variable name
                "totalcartitems": len(request.session["cart_data_obj"]),
                "cart_total_amount": cart_total_amount,
            },
        )
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("core:index")


def delete_item_from_cart(request):
    product_id = str(request.GET["id"])
    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            del request.session["cart_data_obj"][product_id]
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item["qty"]) * float(item["price"])

    context = render_to_string(
        "core/async/cart-list.html",
        {
            "cart_data": request.session["cart_data_obj"],  # Corrected variable name
            "totalcartitems": len(request.session["cart_data_obj"]),
            "cart_total_amount": cart_total_amount,
        },
    )
    return JsonResponse(
        {"data": context, "totalcartitems": len(request.session["cart_data_obj"])}
    )


def update_cart(request):
    product_id = str(request.GET["id"])
    product_qty = request.GET["qty"]

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            cart_data[str(request.GET["id"])]["qty"] = product_qty
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for p_id, item in request.session["cart_data_obj"].items():

templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Checkout
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Checkout</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{totalcartitems}}</span> products in your cart</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <div class="row mb-50">
                    <div class="col-lg-6">
                        <form method="post" class="apply-coupon">
                            <input type="text" placeholder="Enter Coupon Code...">
                            <button class="btn  btn-md" name="login">Apply Coupon</button>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <h4 class="mb-30">Billing Details</h4>
                    <form method="post">
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <input type="text" required="" name="fname" value="{{request.user.username|title}}" placeholder="First name *">
                            </div>
                            <div class="form-group col-lg-6">
                                <input type="text" required="" value="{{active_address.mobile}}" name="lname" placeholder="Mobile No.">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <input type="text" name="billing_address" value="{{active_address.address}}" required="" placeholder="Address *">
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="border p-40 cart-totals ml-30 mb-50">
                    <div class="d-flex align-items-end justify-content-between mb-30">
                        <h4>Your Order</h4>
                        <h6 class="text-muted">Subtotal - <span class="text-brand">₹{{cart_total_amount|floatformat:2}}</span></h6>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mt-30 mb-40">Go Back To Cart</a>
                    
                    <div class="table-responsive order_table checkout">
                        <table class="table no-border">
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                <tr>
                                    <td class="image product-thumbnail"><img src="{{item.image}}" alt="#"></td>
                                    <td>
                                        <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{item.title}}</a></h6></span>
                                    </td>
                                    <td>
                                        <h6 class="text-muted pl-20 pr-20">x {{item.qty}}</h6>
                                    </td>
                                    <td>
                                        <h5 class="text-muted">{{item.price|floatformat:2}}</h5>
                                    </td>
                                    <td>
                                        <h5 class="text-brand">₹{% widthratio item.price 1 item.qty %}</h5>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="payment ml-30">
                    <h4 class="mb-30">Payment</h4>
                    <div class="payment_option">
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                            <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                            <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5" checked="">
                            <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                        </div>
                    </div>
                    <div class="payment-logo d-flex">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                        <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                    </div>
                    <div class="w-50">
                        {{paypal_payment_button.render}}
                    </div>
                    {% comment %} <a href="#" class="btn btn-fill-out btn-block mt-30">Place an Order<i class="fi-rs-sign-out ml-15"></i></a> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/core/order-detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  <main class="main pages">
    <div class="page-header breadcrumb-wrap">
      <div class="container">
        <div class="breadcrumb">
          <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
          <span></span> Pages <span></span> My Account
        </div>
      </div>
    </div>
    <div class="page-content pt-150 pb-150">
      <div class="container">
        <div class="row">
          <div class="col-lg-10 m-auto">
            <div class="row">
              <div class="col-md-3">
                <div class="dashboard-menu">
                  <ul class="nav flex-column" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link"  href="{% url 'core:dashboard' %}" ><i class="fi-rs-settings-sliders mr-10"></i>Dashboard</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" id="orders-tab" data-bs-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false"><i class="fi-rs-shopping-bag mr-10"></i>Orders</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'userauths:sign-out' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-md-9">
                <div class="tab-content account dashboard-content pl-50">
                  {% comment %} <div class="tab-pane fade" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="mb-0">Hello {{ request.user|title }}!</h3>
                      </div>
                      <div class="card-body">
                        <p>
                          From your account dashboard. you can easily check &amp; view your <a href="#">recent orders</a>,<br />
                          manage your <a href="#">shipping and billing addresses</a> and <a href="#">edit your password and account details.</a>
                        </p>
                      </div>
                    </div>
                  </div> {% endcomment %}
                  <div class="tab-pane fade active show" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="mb-0">Your Orders</h3>
                      </div>
                      <div class="card-body">
                        <div class="table-responsive">
                          <table class="table">
                            <thead>
                              <tr>
                                <th>Order Invoice</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Qty</th>
                                <th>Total</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for o in order_items %}
                                <tr>
                                  <td>INV-{{ o.id }}</td>
                                  <td>
                                    <p>
                                        <img src="{{o.image}}" alt="order-image" style="width:60px; height=60px; object-fit;">
                                    </p>
                                  </td>
                                  <td>{{ o.item }}</td>
                                  <td>₹ {{ o.price }}</td>
                                  {% comment %} {% if o.paid_status == True %}
                                    <td>
                                      ✅
                                    </td>
                                  {% else %}
                                  <td class="text-danger"> 
                                    ❌                                   
                                  </td>
                                  {% endif %} {% endcomment %}
                                  <td> {{ o.qty }}</td>
                                  <td>₹ {{ o.total }}</td>
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade" id="track-orders" role="tabpanel" aria-labelledby="track-orders-tab">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="mb-0">Orders tracking</h3>
                      </div>
                      <div class="card-body contact-from-area">
                        <p>To track your order please enter your OrderID in the box below and press "Track" button. This was given to you on your receipt and in the confirmation email you should have received.</p>
                        <div class="row">
                          <div class="col-lg-8">
                            <form class="contact-form-style mt-30 mb-50" action="#" method="post">
                              <div class="input-style mb-20">
                                <label>Order ID</label>
                                <input name="order-id" placeholder="Found in your order confirmation email" type="text" />
                              </div>
                              <div class="input-style mb-20">
                                <label>Billing email</label>
                                <input name="billing-email" placeholder="Email you used during checkout" type="email" />
                              </div>
                              <button class="submit submit-auto-width" type="submit">Track</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade" id="address" role="tabpanel" aria-labelledby="address-tab">
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="card mb-3 mb-lg-0">
                          <div class="card-header">
                            <h3 class="mb-0">Billing Address</h3>
                          </div>
                          <div class="card-body">
                            <address>
                              3522 Interstate<br />
                              75 Business Spur,<br />
                              Sault Ste. <br />Marie, MI 49783
                            </address>
                            <p>New York</p>
                            <a href="#" class="btn-small">Edit</a>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <div class="card">
                          <div class="card-header">
                            <h5 class="mb-0">Shipping Address</h5>
                          </div>
                          <div class="card-body">
                            <address>
                              4299 Express Lane<br />
                              Sarasota, <br />FL 34249 USA <br />Phone: 1.941.227.4444
                            </address>
                            <p>Sarasota</p>
                            <a href="#" class="btn-small">Edit</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade" id="account-detail" role="tabpanel" aria-labelledby="account-detail-tab">
                    <div class="card">
                      <div class="card-header">
                        <h5>Account Details</h5>
                      </div>
                      <div class="card-body">
                        <p>
                          Already have an account? <a href="page-login.html">Log in instead!</a>
                        </p>
                        <form method="post" name="enq">
                          <div class="row">
                            <div class="form-group col-md-6">
                              <label>First Name <span class="required">*</span></label>
                              <input required="" class="form-control" name="name" type="text" />
                            </div>
                            <div class="form-group col-md-6">
                              <label>Last Name <span class="required">*</span></label>
                              <input required="" class="form-control" name="phone" />
                            </div>
                            <div class="form-group col-md-12">
                              <label>Display Name <span class="required">*</span></label>
                              <input required="" class="form-control" name="dname" type="text" />
                            </div>
                            <div class="form-group col-md-12">
                              <label>Email Address <span class="required">*</span></label>
                              <input required="" class="form-control" name="email" type="email" />
                            </div>
                            <div class="form-group col-md-12">
                              <label>Current Password <span class="required">*</span></label>
                              <input required="" class="form-control" name="password" type="password" />
                            </div>
                            <div class="form-group col-md-12">
                              <label>New Password <span class="required">*</span></label>
                              <input required="" class="form-control" name="npassword" type="password" />
                            </div>
                            <div class="form-group col-md-12">
                              <label>Confirm Password <span class="required">*</span></label>
                              <input required="" class="form-control" name="cpassword" type="password" />
                            </div>
                            <div class="col-md-12">
                              <button type="submit" class="btn btn-fill-out submit font-weight-bold" name="submit" value="Submit">Save Change</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/core/test.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

{% endblock %}